/* THE USERS TABLE UP */

CREATE TABLE users (
id SERIAL PRIMARY KEY NOT NULL UNIQUE,
first_name VARCHAR(100) NOT NULL ,
last_name VARCHAR(100) NOT NULL ,
email VARCHAR(255) NOT NULL UNIQUE,
username VARCHAR(100) NOT NULL ,
password VARCHAR(100) NOT NULL);